# NGC 5

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 1. Buatlah Tensor dibawah ini dengan Python:

A = np.array([[23, 50], [7, 12]])
B = np.array([[57, 67], [99, 43]])
C = np.array([[75, 21], [57, 12]])
D = np.array([[87, 26], [18, 84]])

tensor = np.array([A, B, C, D])
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [12]:
# 2. Lakukan perkalian terhadap matrix berikut:

A = np.array([[23, 7, 57], [50, 12, 67], [19, 109, 98]])
B = np.array([[17, 22, 19]])
print(A,B)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]] [[17 22 19]]


In [4]:
A * B

array([[ 391,  154, 1083],
       [ 850,  264, 1273],
       [ 323, 2398, 1862]])

In [11]:
# 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

A = np.array([[23, 7, 57], [50, 12, 67], [19, 109, 98]])
A

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [14]:
# Transpose

A_trns = A.T
A_trns

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [15]:
# Determinan

np.linalg.det(A)

131343.99999999997

In [16]:
np.linalg.det(A_trns)

131344.0000000002

In [17]:
# Inverse
np.linalg.inv(A)

array([[-0.0466485 ,  0.04208034, -0.00163692],
       [-0.02761451,  0.00891552,  0.0099662 ],
       [ 0.03975819, -0.01807467, -0.00056341]])

In [18]:
np.linalg.inv(A_trns)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])